// Generated by gencpp from file mr_msgs/PlannerResult.msg
// DO NOT EDIT!


#ifndef MR_MSGS_MESSAGE_PLANNERRESULT_H
#define MR_MSGS_MESSAGE_PLANNERRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mr_msgs
{
template <class ContainerAllocator>
struct PlannerResult_
{
  typedef PlannerResult_<ContainerAllocator> Type;

  PlannerResult_()
    : header()
    , algorithm()
    , path_length(0.0)
    , planning_time(0.0)
    , num_waypoints(0)
    , success(false)  {
    }
  PlannerResult_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , algorithm(_alloc)
    , path_length(0.0)
    , planning_time(0.0)
    , num_waypoints(0)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _algorithm_type;
  _algorithm_type algorithm;

   typedef double _path_length_type;
  _path_length_type path_length;

   typedef double _planning_time_type;
  _planning_time_type planning_time;

   typedef int32_t _num_waypoints_type;
  _num_waypoints_type num_waypoints;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::mr_msgs::PlannerResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mr_msgs::PlannerResult_<ContainerAllocator> const> ConstPtr;

}; // struct PlannerResult_

typedef ::mr_msgs::PlannerResult_<std::allocator<void> > PlannerResult;

typedef boost::shared_ptr< ::mr_msgs::PlannerResult > PlannerResultPtr;
typedef boost::shared_ptr< ::mr_msgs::PlannerResult const> PlannerResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mr_msgs::PlannerResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mr_msgs::PlannerResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mr_msgs::PlannerResult_<ContainerAllocator1> & lhs, const ::mr_msgs::PlannerResult_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.algorithm == rhs.algorithm &&
    lhs.path_length == rhs.path_length &&
    lhs.planning_time == rhs.planning_time &&
    lhs.num_waypoints == rhs.num_waypoints &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mr_msgs::PlannerResult_<ContainerAllocator1> & lhs, const ::mr_msgs::PlannerResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mr_msgs::PlannerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mr_msgs::PlannerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mr_msgs::PlannerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mr_msgs::PlannerResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mr_msgs::PlannerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mr_msgs::PlannerResult_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mr_msgs::PlannerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef19d2ad7038d14cfe1f591d32dcfcbf";
  }

  static const char* value(const ::mr_msgs::PlannerResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef19d2ad7038d14cULL;
  static const uint64_t static_value2 = 0xfe1f591d32dcfcbfULL;
};

template<class ContainerAllocator>
struct DataType< ::mr_msgs::PlannerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mr_msgs/PlannerResult";
  }

  static const char* value(const ::mr_msgs::PlannerResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mr_msgs::PlannerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Benchmark result for a single planning run.\n"
"Header header\n"
"\n"
"# Algorithm identifier, e.g. \"astar\", \"bcd\".\n"
"string algorithm\n"
"\n"
"# Total path length in meters.\n"
"float64 path_length\n"
"\n"
"# Wall-clock planning time in seconds.\n"
"float64 planning_time\n"
"\n"
"# Number of waypoints in the published path.\n"
"int32 num_waypoints\n"
"\n"
"# True if the planner found a feasible path.\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mr_msgs::PlannerResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mr_msgs::PlannerResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.algorithm);
      stream.next(m.path_length);
      stream.next(m.planning_time);
      stream.next(m.num_waypoints);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannerResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mr_msgs::PlannerResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mr_msgs::PlannerResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "algorithm: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.algorithm);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "path_length: ";
    Printer<double>::stream(s, indent + "  ", v.path_length);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "planning_time: ";
    Printer<double>::stream(s, indent + "  ", v.planning_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num_waypoints: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_waypoints);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MR_MSGS_MESSAGE_PLANNERRESULT_H
